# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        xcodebuild clean test -project VocabularyApp.xcodeproj \
        -scheme VocabularyApp \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
